// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sms.proto

package example.akka.actortest.grpc;

public final class SmsActorGrpc {
  private SmsActorGrpc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_actortest_SmsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_actortest_SmsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_actortest_SmsReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_actortest_SmsReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\tsms.proto\022\tactortest\"3\n\nSmsRequest\022\014\n\004" +
      "from\030\001 \001(\t\022\n\n\002to\030\002 \001(\t\022\013\n\003sms\030\003 \001(\t\"1\n\010S" +
      "msReply\022\014\n\004from\030\001 \001(\t\022\n\n\002to\030\002 \001(\t\022\013\n\003sms" +
      "\030\003 \001(\t2I\n\016SmsGrpcService\0227\n\007sendSms\022\025.ac" +
      "tortest.SmsRequest\032\023.actortest.SmsReply\"" +
      "\000B-\n\033example.akka.actortest.grpcB\014SmsAct" +
      "orGrpcP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_actortest_SmsRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_actortest_SmsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_actortest_SmsRequest_descriptor,
        new String[] { "From", "To", "Sms", });
    internal_static_actortest_SmsReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_actortest_SmsReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_actortest_SmsReply_descriptor,
        new String[] { "From", "To", "Sms", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
